language: javascript

services:
  - docker

env:
  NODE_ENV: development
  SERVER_PORT: 8000
  MYSQL_RANDOM_ROOT_PASSWORD: true
  MYSQL_HOST: db
  MYSQL_PORT: 3367
  MYSQL_USER: jb_ci
  MYSQL_PASSWORD: jb_ci
  MYSQL_DATABASE: jb_ci

before_install:
  # set up secrets
- docker swarm init
- echo "$NODE_ENV" | docker secret create NODE_ENV -
- echo "$SERVER_PORT" | docker secret create SERVER_PORT -
- echo "$MYSQL_RANDOM_ROOT_PASSWORD" | docker secret create MYSQL_RANDOM_ROOT_PASSWORD -
- echo "$MYSQL_HOST" | docker secret create MYSQL_HOST -
- echo "$MYSQL_PORT" | docker secret create MYSQL_PORT -
- echo "$MYSQL_USER" | docker secret create MYSQL_USER -
- echo "$MYSQL_PASSWORD" | docker secret create MYSQL_PASSWORD -
- echo "$MYSQL_DATABASE" | docker secret create MYSQL_DATABASE -
  # build
- docker-compose build
- docker-compose run db
  # sleep to allow db to initialise
- sleep 10
  # start the api
- docker-compose run api

script:
  - cd backend && yarn travis:test