language: javascript

services:
  - docker

before_install:
- docker-compose build
- docker-compose run db
- sleep 10
- docker-compose run api
- cd backend && yarn install

script:
  - cd backend && yarn travis:test