language: javascript

services:
  - docker

env:
  NODE_ENV: development
  SERVER_PORT: 8000
  MYSQL_RANDOM_ROOT_PASSWORD: true
  MYSQL_HOST: db
  MYSQL_PORT: 3367
  MYSQL_USER: jb_ci
  MYSQL_PASSWORD: jb_ci
  MYSQL_DATABASE: jb_ci

before_install:
  # set up secrets
- echo "$NODE_ENV" > /run/secrets/NODE_ENV
- echo "$SERVER_PORT" > /run/secrets/SERVER_PORT
- echo "$MYSQL_RANDOM_ROOT_PASSWORD" > /run/secrets/MYSQL_RANDOM_ROOT_PASSWORD
- echo "$MYSQL_HOST" > /run/secrets/MYSQL_HOST
- echo "$MYSQL_PORT" > /run/secrets/MYSQL_PORT
- echo "$MYSQL_USER" > /run/secrets/MYSQL_USER
- echo "$MYSQL_PASSWORD" > /run/secrets/MYSQL_PASSWORD
- echo "$MYSQL_DATABASE" > /run/secrets/MYSQL_DATABASE
  # build
- docker-compose build
- docker-compose run db
  # sleep to allow db to initialise
- sleep 10
  # start the api
- docker-compose run api

script:
  - cd backend && yarn travis:test