language: javascript

services:
  - docker

env:
  NODE_ENV: development
  SERVER_PORT: 8000
  MYSQL_RANDOM_ROOT_PASSWORD: true
  MYSQL_HOST: db
  MYSQL_PORT: 3367
  MYSQL_USER: jb_ci
  MYSQL_PASSWORD: jb_ci
  MYSQL_DATABASE: jb_ci

before_install:
  # set up secrets
- kubectl create secret generic NODE_ENV --from-literal=$NODE_ENV
- kubectl create secret generic SERVER_PORT --from-literal=$SERVER_PORT
- kubectl create secret generic MYSQL_RANDOM_ROOT_PASSWORD --from-literal=$MYSQL_RANDOM_ROOT_PASSWORD
- kubectl create secret generic MYSQL_HOST --from-literal=$MYSQL_HOST
- kubectl create secret generic MYSQL_POST --from-literal=$MYSQL_PORT
- kubectl create secret generic MYSQL_USER --from-literal=$MYSQL_USER
- kubectl create secret generic MYSQL_PASSWORD --from-literal=$MYSQL_PASSWORD
- kubectl create secret generic MYSQL_DATABASE --from-literal=$MYSQL_DATABASE
  # build
- docker-compose build
- docker-compose run db
  # sleep to allow db to initialise
- sleep 10
  # start the api
- docker-compose run api

script:
  - cd backend && yarn travis:test