language: javascript

services:
  - docker


before_install:
  # build
- docker-compose build
- docker-compose run db
  # sleep to allow db to initialise
- sleep 10
  # start the api
- docker-compose run api

script:
  - cd backend && yarn travis:test