language: node_js
node_js:
  - lts/*

services:
  - docker


before_install:
  # build
- docker-compose build
- docker-compose run -d db
  # sleep to allow db to initialise
- sleep 10
  # start the api
- docker-compose run -d api

script:
  - cd backend && yarn install && yarn travis:test