version: '3.3'
services:
  api:
    env_file:
      - .env
    build:
      context: ./backend
    ports:
      - "8080:8080"
    expose:
      - 8080
  frontend:
    env_file:
      - .env
    build:
      context: ./frontend
      args:
        jobs_board_api_url: "http://sirius:8080"
    ports:
      - "8081:80"
    expose:
      - 8081
