version: '3.3'
services:
  api:
    environment:
      - NODE_ENV=${NODE_ENV}
    build:
      context: .
      dockerfile: ./backend/Dockerfile
    volumes:
      - ./backend:/app
    ports:
      - "8080:8080"
    expose:
      - 8080
  frontend:
    environment:
      - NODE_ENV=${NODE_ENV}
    build:
      context: .
      dockerfile: ./frontend/Dockerfile
    volumes:
      - ./frontend:/app
