version: '3.3'
services:
  api:
    env_file:
      - .env
    build:
      context: ./backend
    image: webpersonal.azurecr.io/jb-api:latest
    ports:
      - "8080:8080"
    expose:
      - 8080
    environment:
      MAIL_SMTP_SERVER: /run/secrets/MAIL_SMTP_SERVER
      MAIL_SMTP_SERVER_PORT: /run/secrets/MAIL_SMTP_SERVER_PORT
      MAIL_USERNAME: /run/secrets/MAIL_USERNAME
      MAIL_PASSWORD: /run/secrets/MAIL_PASSWORD
  frontend:
    env_file:
      - .env
    build:
      context: ./frontend
    image: webpersonal.azurecr.io/jb-frontend:latest
    ports:
      - "8081:80"
    expose:
      - 8081
  database:
    image: mariadb:latest
    ports:
      - "3306:3306"
    expose:
      - 3306
    volumes:
      - ./backend/db/mysql:/var/lib/mysql
    environment:
      - MYSQL_RANDOM_ROOT_PASSWORD=true
      - MYSQL_LOG_CONSOLE=true
      - MYSQL_DATABASE=test
      - MYSQL_USER=jb
      - MYSQL_PASSWORD=jb
      # MYSQL_DATABASE: /run/secrets/MYSQL_DATABASE
      # MYSQL_USER: /run/secrets/MYSQL_USER
      # MYSQL_PASSWORD: /run/secrets/MYSQL_PASSWORD


secrets:
  MAIL_SMTP_SERVER:
    external: true
  MAIL_SMTP_SERVER_PORT:
    external: true
  MAIL_USERNAME:
    external: true
  MAIL_PASSWORD:
    external: true
  MYSQL_DATABASE:
    external: true
  MYSQL_USER:
    external: true
  MYSQL_PASSWORD:
    external: true
    
