version: '3.3'
services:
  api:
    build:
      context: ./backend
    image: webpersonal.azurecr.io/jb-api:latest
    ports:
      - "8080:8080"
    expose:
      - 8080
    env_file:
      - .env
      - ./backend/.env
  frontend:
    env_file:
      - .env
    build:
      context: ./frontend
    image: webpersonal.azurecr.io/jb-frontend:latest
    ports:
      - "8081:80"
    expose:
      - 8081
  db:
    image: mariadb:latest
    ports:
      - "3306:3306"
    expose:
      - 3306
    env_file:
      - ./backend/.env

secrets:
  MAIL_SMTP_SERVER:
    external: true
  MAIL_SMTP_SERVER_PORT:
    external: true
  MAIL_USERNAME:
    external: true
  MAIL_PASSWORD:
    external: true
  MYSQL_DATABASE:
    external: true
  MYSQL_USER:
    external: true
  MYSQL_PASSWORD:
    external: true
    
